# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: 20
      - run: bun ci
      - run: bunx playwright install --with-deps
      - run: bun test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: bun ci
      - run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
